import React from 'react'
import styled from 'styled-components'
import SectionTitle from './SectionTitle'

const BlogStyle = styled.div`
padding: 5rem 0 0;
`;

function Blog() {
  return (

    <BlogStyle>
    <div className='container'>
        <SectionTitle
        heading='BLOG'
        subheading='my Blog is here' />

        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic dignissimos animi ratione, nam nihil dolores eius ipsam natus, praesentium quae laborum qui dolor, suscipit consequuntur fuga quasi blanditiis ad id nisi reiciendis corporis quia. Veritatis dolore, iusto nesciunt est ea repellat quae rem quos voluptates, quisquam autem ipsum saepe esse deserunt dolorem voluptatum! Nisi et, officiis odit cumque soluta mollitia molestias, delectus eum alias ea quam! Molestias, sunt. Blanditiis tempora sequi, voluptate non dicta doloribus enim. Obcaecati nam, neque libero porro animi voluptas omnis saepe. Impedit suscipit nihil magnam in eaque animi accusamus sit sequi corporis recusandae, ut ex pariatur.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic dignissimos animi ratione, nam nihil dolores eius ipsam natus, praesentium quae laborum qui dolor, suscipit consequuntur fuga quasi blanditiis ad id nisi reiciendis corporis quia. Veritatis dolore, iusto nesciunt est ea repellat quae rem quos voluptates, quisquam autem ipsum saepe esse deserunt dolorem voluptatum! Nisi et, officiis odit cumque soluta mollitia molestias, delectus eum alias ea quam! Molestias, sunt. Blanditiis tempora sequi, voluptate non dicta doloribus enim. Obcaecati nam, neque libero porro animi voluptas omnis saepe. Impedit suscipit nihil magnam in eaque animi accusamus sit sequi corporis recusandae, ut ex pariatur.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic dignissimos animi ratione, nam nihil dolores eius ipsam natus, praesentium quae laborum qui dolor, suscipit consequuntur fuga quasi blanditiis ad id nisi reiciendis corporis quia. Veritatis dolore, iusto nesciunt est ea repellat quae rem quos voluptates, quisquam autem ipsum saepe esse deserunt dolorem voluptatum! Nisi et, officiis odit cumque soluta mollitia molestias, delectus eum alias ea quam! Molestias, sunt. Blanditiis tempora sequi, voluptate non dicta doloribus enim. Obcaecati nam, neque libero porro animi voluptas omnis saepe. Impedit suscipit nihil magnam in eaque animi accusamus sit sequi corporis recusandae, ut ex pariatur.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic dignissimos animi ratione, nam nihil dolores eius ipsam natus, praesentium quae laborum qui dolor, suscipit consequuntur fuga quasi blanditiis ad id nisi reiciendis corporis quia. Veritatis dolore, iusto nesciunt est ea repellat quae rem quos voluptates, quisquam autem ipsum saepe esse deserunt dolorem voluptatum! Nisi et, officiis odit cumque soluta mollitia molestias, delectus eum alias ea quam! Molestias, sunt. Blanditiis tempora sequi, voluptate non dicta doloribus enim. Obcaecati nam, neque libero porro animi voluptas omnis saepe. Impedit suscipit nihil magnam in eaque animi accusamus sit sequi corporis recusandae, ut ex pariatur.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic dignissimos animi ratione, nam nihil dolores eius ipsam natus, praesentium quae laborum qui dolor, suscipit consequuntur fuga quasi blanditiis ad id nisi reiciendis corporis quia. Veritatis dolore, iusto nesciunt est ea repellat quae rem quos voluptates, quisquam autem ipsum saepe esse deserunt dolorem voluptatum! Nisi et, officiis odit cumque soluta mollitia molestias, delectus eum alias ea quam! Molestias, sunt. Blanditiis tempora sequi, voluptate non dicta doloribus enim. Obcaecati nam, neque libero porro animi voluptas omnis saepe. Impedit suscipit nihil magnam in eaque animi accusamus sit sequi corporis recusandae, ut ex pariatur.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic dignissimos animi ratione, nam nihil dolores eius ipsam natus, praesentium quae laborum qui dolor, suscipit consequuntur fuga quasi blanditiis ad id nisi reiciendis corporis quia. Veritatis dolore, iusto nesciunt est ea repellat quae rem quos voluptates, quisquam autem ipsum saepe esse deserunt dolorem voluptatum! Nisi et, officiis odit cumque soluta mollitia molestias, delectus eum alias ea quam! Molestias, sunt. Blanditiis tempora sequi, voluptate non dicta doloribus enim. Obcaecati nam, neque libero porro animi voluptas omnis saepe. Impedit suscipit nihil magnam in eaque animi accusamus sit sequi corporis recusandae, ut ex pariatur.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic dignissimos animi ratione, nam nihil dolores eius ipsam natus, praesentium quae laborum qui dolor, suscipit consequuntur fuga quasi blanditiis ad id nisi reiciendis corporis quia. Veritatis dolore, iusto nesciunt est ea repellat quae rem quos voluptates, quisquam autem ipsum saepe esse deserunt dolorem voluptatum! Nisi et, officiis odit cumque soluta mollitia molestias, delectus eum alias ea quam! Molestias, sunt. Blanditiis tempora sequi, voluptate non dicta doloribus enim. Obcaecati nam, neque libero porro animi voluptas omnis saepe. Impedit suscipit nihil magnam in eaque animi accusamus sit sequi corporis recusandae, ut ex pariatur.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic dignissimos animi ratione, nam nihil dolores eius ipsam natus, praesentium quae laborum qui dolor, suscipit consequuntur fuga quasi blanditiis ad id nisi reiciendis corporis quia. Veritatis dolore, iusto nesciunt est ea repellat quae rem quos voluptates, quisquam autem ipsum saepe esse deserunt dolorem voluptatum! Nisi et, officiis odit cumque soluta mollitia molestias, delectus eum alias ea quam! Molestias, sunt. Blanditiis tempora sequi, voluptate non dicta doloribus enim. Obcaecati nam, neque libero porro animi voluptas omnis saepe. Impedit suscipit nihil magnam in eaque animi accusamus sit sequi corporis recusandae, ut ex pariatur.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic dignissimos animi ratione, nam nihil dolores eius ipsam natus, praesentium quae laborum qui dolor, suscipit consequuntur fuga quasi blanditiis ad id nisi reiciendis corporis quia. Veritatis dolore, iusto nesciunt est ea repellat quae rem quos voluptates, quisquam autem ipsum saepe esse deserunt dolorem voluptatum! Nisi et, officiis odit cumque soluta mollitia molestias, delectus eum alias ea quam! Molestias, sunt. Blanditiis tempora sequi, voluptate non dicta doloribus enim. Obcaecati nam, neque libero porro animi voluptas omnis saepe. Impedit suscipit nihil magnam in eaque animi accusamus sit sequi corporis recusandae, ut ex pariatur.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic dignissimos animi ratione, nam nihil dolores eius ipsam natus, praesentium quae laborum qui dolor, suscipit consequuntur fuga quasi blanditiis ad id nisi reiciendis corporis quia. Veritatis dolore, iusto nesciunt est ea repellat quae rem quos voluptates, quisquam autem ipsum saepe esse deserunt dolorem voluptatum! Nisi et, officiis odit cumque soluta mollitia molestias, delectus eum alias ea quam! Molestias, sunt. Blanditiis tempora sequi, voluptate non dicta doloribus enim. Obcaecati nam, neque libero porro animi voluptas omnis saepe. Impedit suscipit nihil magnam in eaque animi accusamus sit sequi corporis recusandae, ut ex pariatur.</p>
    </div>
    </BlogStyle>
  )
}

export default Blog